realdebridmanager:
    image: hyperbunny77/realdebridmanager:2022.06.27   #Change to the latest release
    container_name: realdebridmanager
    environment:
      - rdmport=5000    # WebUI Port
    ports:
      - 5000:5000/tcp 	#Change second value if changed above
    volumes:
      - torrent_folder_to_watch:/watch
      - path_for_config_storage:/config
    restart: unless-stopped
